# =============================================================================
# zenml-cloudrun-service.yaml
#
# Cloud Run service definition for ZenML Server with a Cloud SQL Auth Proxy
# sidecar running in TCP mode.
#
# WHY A SIDECAR?
# ZenML's URL validator rejects ?unix_socket=... query parameters, so the
# built-in --add-cloudsql-instances flag (which only provides Unix sockets)
# cannot be used. Instead, we run the Cloud SQL Auth Proxy as a sidecar
# container in TCP mode, listening on 127.0.0.1:3306.
#
# Placeholders (replaced by deploy_zenml.sh at deploy time):
#   __IMAGE__                    → ZenML server Docker image URI
#   __SA_EMAIL__                 → Service account email
#   __INSTANCE_CONNECTION_NAME__ → Cloud SQL instance connection string
#   __DB_USER__                  → Database username
#   __ZENML_DB__                 → Database name
#   __SECRET_NAME__              → Secret Manager secret name for DB password
#   __REGION__                   → GCP region
# =============================================================================
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zenml-server
  labels:
    cloud.googleapis.com/location: __REGION__
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
        run.googleapis.com/startup-cpu-boost: "true"
        # Ensure the proxy sidecar is healthy BEFORE ZenML starts.
        # This prevents ZenML from crashing on DB connection during boot.
        run.googleapis.com/container-dependencies: '{"zenml-server":["cloud-sql-proxy"]}'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 600
      serviceAccountName: __SA_EMAIL__
      containers:
        # ----- Primary container: ZenML Server -----
        - name: zenml-server
          image: __IMAGE__
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
          env:
            - name: INSTANCE_CONNECTION_NAME
              value: __INSTANCE_CONNECTION_NAME__
            - name: DB_USER
              value: __DB_USER__
            - name: ZENML_DB
              value: __ZENML_DB__
            - name: ZENML_STORE_TYPE
              value: sql
            - name: ZENML_CONTAINER
              value: "true"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: __SECRET_NAME__
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 18
            timeoutSeconds: 5

        # ----- Sidecar: Cloud SQL Auth Proxy (TCP mode) -----
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.3
          args:
            - "--port=3306"
            - "--health-check"
            - "--http-address=0.0.0.0"
            - "--http-port=9090"
            - "__INSTANCE_CONNECTION_NAME__"
          resources:
            limits:
              memory: 256Mi
              cpu: "0.5"
          startupProbe:
            httpGet:
              path: /startup
              port: 9090
            initialDelaySeconds: 2
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 3
  traffic:
    - percent: 100
      latestRevision: true
