steps:
  # 1. Build the container image
  # We use the standard docker builder.
  # We use --cache-from to speed up builds if the 'latest' tag exists.
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'mlops_pipeline'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull $_IMAGE_URI:latest || true
        docker build \
          --cache-from $_IMAGE_URI:latest \
          -t $_IMAGE_URI:$SHORT_SHA \
          -t $_IMAGE_URI:latest \
          .

  # 2. Validation (CI)
  # Run the pipeline compilation inside the container we just built.
  # This verifies that:
  #   a) The container runs successfully (dependencies are correct).
  #   b) The Python code is syntax-free and imports work.
  #   c) KFP compiles the pipeline definition correctly.
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'mlops_pipeline'
    args: ['run', '$_IMAGE_URI:$SHORT_SHA', 'python', 'manage.py', 'compile']

  # 3. Push the images to Artifact Registry
  # This happens automatically via the 'images' field below, 
  # but declaring it ensures explicit control if needed.
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'mlops_pipeline'
    args: ['push', '$_IMAGE_URI:$SHORT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'mlops_pipeline'
    args: ['push', '$_IMAGE_URI:latest']

# Substitutions allow variables to be passed at trigger time or inferred.
substitutions:
  _PROJECT_ID: 'realtime-headway-prediction' # Default, can be overridden by Trigger
  # Using the specific Artifact Registry path we established
  _IMAGE_URI: 'us-docker.pkg.dev/${_PROJECT_ID}/headway-pipelines/training'

# Output images to be pushed
images:
  - '$_IMAGE_URI:$SHORT_SHA'
  - '$_IMAGE_URI:latest'

# Timeout for the build
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
